### ISSUE TITLE
Update all modules according to linting guideline

### ISSUE THREAD

**Issue by FendVario1** [amosproj/amos2022ss01-firmware-downloader#125]
## User story
1. As a developer
2. I want / need all modules to be updates
3. So that the automated linting works as expected.

## Acceptance criteria
* No python file throws a linting error

## Definition of done (DoD)
* Code is complete
* Code is uploaded in GitHub
* Fulfills the acceptance criteria in the User Story
* Documentation has been updated
* Functionality has been reviewed
* Only MIT-Licensed Libraries are used
* Create tests necessary to ensure feature is working
* Bill of Materials updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by bilalasgharaziz** [comment]
Linting issues for schnieder_electric and ABB are fixed.
