### ISSUE TITLE
Save metadata to database

### ISSUE THREAD

**Issue by FloSchels** [amosproj/amos2022ss01-firmware-downloader#27]
## User story
1. As a user
2. I want the extracted metadata to be saved to the database
3. So that I can start further analysis processes

## Acceptance criteria
* Complete: all extracted metadata is saved
* Correct: Metadata is saved to the right columns

## Definition of done (DoD)
* Code is complete
* Code is uploaded in GitHub
* Fulfills the acceptance criteria in the User Story
* Documentation has been updated
* Functionality has been reviewed
* Only MIT-Licensed Libraries are used
* Create tests necessary to ensure feature is working
* Bill of Materials updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by TejeshPala** [comment]
The DB is enhanced with test functionality as an input as per the https://github.com/amosproj/amos2022ss01-firmware-downloader/issues/27 and added additional functionality such as logging in-order to back trace the working of DB if any issues in data

**Comment by TejeshPala** [comment]
https://github.com/amosproj/amos2022ss01-firmware-downloader/tree/TejeshPala/sprint-05

**Comment by TejeshPala** [comment]
https://github.com/amosproj/amos2022ss01-firmware-downloader/blob/development/database.py
and
https://github.com/amosproj/amos2022ss01-firmware-downloader/blob/development/test_database.py
