### ISSUE TITLE
Update vendor modules

### ISSUE THREAD

**Issue by FloSchels** [amosproj/amos2022ss01-firmware-downloader#75]
## User story
1. As a user
2. I want / need all vendor modules to conform to the same standards
3. So that there are no exceptions from the standard that lower maintainability

## Acceptance criteria
* Update code to conform to error tolerant environment
* Credentials and links to the download area are retrieved from the config, not hard-coded
* All modules use one single log file

## Definition of done (DoD)
* Code is complete
* Code is uploaded in GitHub
* Fulfills the acceptance criteria in the User Story
* Documentation has been updated
* Functionality has been reviewed
* Only MIT-Licensed Libraries are used
* Create tests necessary to ensure feature is working
* Bill of Materials updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by FendVario1** [comment]
Main Dev is @tariqmagsi
