### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by FloSchels** [amosproj/amos2022ss01-firmware-downloader#76]
## User story
1. As a user
2. I want / need an installation script 
3. So that all dependencies are installed automattically and the environment is set for the firmware scraper

## Acceptance criteria
* Installation script that installs all neccessary dependencies automatically
* refer to https://github.com/e-m-b-a/emba/blob/master/installer.sh and https://github.com/e-m-b-a/embark/blob/main/installer.sh
* script should create database user with random password; username and password should be saved in config file (refer to embark script)

## Definition of done (DoD)
* Code is complete
* Code is uploaded in GitHub
* Fulfills the acceptance criteria in the User Story
* Documentation has been updated
* Functionality has been reviewed
* Only MIT-Licensed Libraries are used
* Create tests necessary to ensure feature is working
* Bill of Materials updated

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by FendVario1** [comment]
Please use proper JSON and put the identifiers into quotation marks.

**Comment by FendVario1** [comment]
Also as I can see it the password is neither set on the database nor used by the database module

**Comment by FendVario1** [comment]
And the GitHub Action for shell check failed. If this is not fixed for the release candidate we will not accept the issue.
